### ISSUE TITLE
XXXX.yaml contains an invalid HorizontalPodAutoscaler

### ISSUE THREAD

**Issue by emas80** [instrumenta/kubeval#57]
Hi, I have a (correct) horizontal pod autoscaler definition, running on Kubernetes 1.7.11

When I launch kubeval with the -strict, even with -v 1.7.11, I get 
core-api.yaml contains an invalid HorizontalPodAutoscaler
---> targetCPUUtilizationPercentage: Additional property targetCPUUtilizationPercentage is not allowed

But the property is correct. By removing the -strict the file is considered correct.
I need the -strict because I must be able to understand if some yaml contains values rejected by kubectl (e.g. adding a real not supported property)

Any ideas on why it tells me it is wrong? This is preventing us from adding this very useful script to our CI/CD release pipeline.

**Comment by garethr** [comment]
Mmm, thanks for reporting. Would you be able to provide a sample YAML file that fails? I'll add that to the test suite and investigate what's happening. It might be an issue with the generated schemas, or a problem with the upstream openapi descriptions.

**Comment by emas80** [comment]
Hi @garethr , the sample yaml at the bottom of the Kubernetes documentation would fail the validation if you use --strict

https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/

[autoscaler.yaml.txt](https://github.com/garethr/kubeval/files/1755207/autoscaler.yaml.txt)

**Comment by garethr** [comment]
Mmm, so `targetCPUUtilizationPercentage` isn't in the Schema until 1.8.x. That means it's not described in the OpenAPI description for 1.7.x. I presume when you submit a document using this to your 1.7.x cluster it works? If so a few things could be up:

1. You have a version of kubectl from 1.8.x onwards
2. It's a bug in the OpenAPI description (I've found a few of these and am reporting upstream)
3. Something else

Could you check what version of `kubectl` you're running:

```
kubectl version
```

**Comment by emas80** [comment]
I'm running version 

Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.1", GitCommit:"1dc5c66f5dd61da08412a74221ecc79208c2165b", GitTreeState:"clean", BuildDate:"2017-07-14T02:00:46Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

How does this have an impact?

I don't understand, targetCPUUtilizationPercentage is working in Kubernetes 1.7.x, we are using it right now on production. I cannot be sure about 1.6.x because i was not using it back then.
I think that there might be a bug in the open api description then.

I don't know if this is related, but checking https://github.com/garethr/kubernetes-json-schema/blob/master/v1.7.11/horizontalpodautoscalerspec.json seems the property is there.

**Comment by garethr** [comment]
Ah, so it's in the spec but not the main object schemas? A quick check to verify that:

Schema | Includes targetCPUUtilizationPercentage 
--- | ---
v1.7.11/horizontalpodautoscalerspec.json | True
v1.7.11/horizontalpodautoscaler.json | False
v1.7.11-standalone/horizontalpodautoscalerspec.json 
v1.7.11-standalone/horizontalpodautoscaler.json | False
v1.7.11-standalone-strict/horizontalpodautoscaler.json | False
v1.7.11-standalone-strict/horizontalpodautoscalerspec.json

Going to the source: https://raw.githubusercontent.com/kubernetes/kubernetes/v1.7.11/api/openapi-spec/swagger.json I can see the problem:

`targetCPUUtilizationPercentage` is present in `io.k8s.kubernetes.pkg.apis.autoscaling.v1.HorizontalPodAutoscalerSpec` but NOT in `io.k8s.kubernetes.pkg.apis.autoscaling.v2alpha1.HorizontalPodAutoscalerSpec`

At the moment the schemas (specifically the tools used to generate them from the OpenAPI description) don't account for the drift between versions. And `kubeval` is just using the type rather than the resource version to look up the correct schema.

This isn't specific to this resource, but a wider problem. I'll definitely be looking at fixing when I get a moment. Thanks for providing the details.

**Comment by emas80** [comment]
I'm glad I could help, thank you for being so fast fixing the problem!

**Comment by emas80** [comment]
I'm glad I could help

**Comment by johanneswuerbach** [comment]
@garethr I took a pass at trying to fix that https://github.com/garethr/kubeval/pull/63, let me know what you think.

**Comment by garethr** [comment]
This issue should now be resolved. The latest version of Kubeval correctly handles different resource versions. If you still have an issue please do reopen.

**Comment by davidmalott** [comment]
I am seeing this error: `WARN - web_hpa.yaml contains an invalid HorizontalPodAutoscaler (app-x-hpa) - targetCPUUtilizationPercentage: Additional property targetCPUUtilizationPercentage is not allowed`

 using flags --openshift --strict -v 3.11.0 on the following yaml construct:

`apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: app-x-hpa
spec:
  maxReplicas: 15
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app-x-deployment
  targetCPUUtilizationPercentage: 60
status:
  conditions: []
  currentMetrics: []
  currentReplicas: 0
  desiredReplicas: 0`

furthermore, the status values are not required, yet --strict fails if they are not defined.

Using kubeval version :
`15:03 $ kubeval --version
Version: 0.16.1
Commit: f5dba6b486fa18b9179b91e15eb6f2b0f7a5a69e
Date: 2021-03-30T15:17:06Z`
